### PR TITLE
Less intrusive aproach with mocked test

### PR DESCRIPTION
**Pull request by josejuanmontiel**
Here @saniales a different aproach of #16 with mocked (faked) test :D 

I think the original code was nearly correct, about the problem of rename in different partitions.

This approach (with it's finalized) i thinks it's more in the shape of the original code :)

### CODE REVIEW

**Comment by josejuanmontiel** [comment]
The problem with original solution was with _, copyErr := io.Copy(mongodFile, mongodTmpFile) fails because the preveius rename "close" the file... this solution i think it's more general...

**Comment by josejuanmontiel** [comment]
@saniales  i updated the go.sum ;)

**Comment by saniales** [comment]
@josejuanmontiel please run a `go mod tidy` and update go.mod and go.sum with this command

**Comment by saniales** [comment]
Thank you very much @josejuanmontiel the Tryvium Team will contact you on your personal mail to establish a fruitful cooperation for the future 👍

**Pull request merged**
